# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.setWindowModality(QtCore.Qt.NonModal)
        Form.setEnabled(True)
        Form.resize(1200, 610)
        Form.setMinimumSize(QtCore.QSize(0, 0))
        Form.setMaximumSize(QtCore.QSize(1400, 800))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        Form.setFont(font)
        Form.setFocusPolicy(QtCore.Qt.NoFocus)
        Form.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        Form.setAcceptDrops(False)
        Form.setAutoFillBackground(False)
        Form.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.tabWidget = QtWidgets.QTabWidget(Form)
        self.tabWidget.setGeometry(QtCore.QRect(0, 10, 1200, 600))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(12)
        self.tabWidget.setFont(font)
        self.tabWidget.setObjectName("tabWidget")
        self.tab_1 = QtWidgets.QWidget()
        self.tab_1.setObjectName("tab_1")
        self.widget_id6 = QtWidgets.QWidget(self.tab_1)
        self.widget_id6.setGeometry(QtCore.QRect(240, 450, 120, 110))
        self.widget_id6.setStyleSheet("background-color: rgb(255, 165, 0, 200);\n"
"border-radius:10px;")
        self.widget_id6.setObjectName("widget_id6")
        self.label_ID6 = QtWidgets.QLabel(self.widget_id6)
        self.label_ID6.setGeometry(QtCore.QRect(50, 0, 32, 20))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        self.label_ID6.setFont(font)
        self.label_ID6.setStyleSheet("background-color: rgb(255, 255, 255， 0);\n"
"border-radius:0px;")
        self.label_ID6.setObjectName("label_ID6")
        self.horizontalSlider_pulse_6 = QtWidgets.QSlider(self.widget_id6)
        self.horizontalSlider_pulse_6.setGeometry(QtCore.QRect(10, 20, 100, 22))
        self.horizontalSlider_pulse_6.setAutoFillBackground(False)
        self.horizontalSlider_pulse_6.setStyleSheet("QSlider{\n"
"    border-radius:0px;\n"
"     background-color: rgb(0, 0, 0);\n"
"}\n"
"\n"
"QSlider::handle {/*设置中间的那个滑动的键*/                           \n"
"    border: 10px solid rgb(255, 255, 255)\n"
"}\n"
"QSlider::handle:horizontal{\n"
"    width: -1px;\n"
"    margin: -4px; /* height */\n"
"}\n"
"QSlider::groove{\n"
"    background: rgb(10, 150, 200);\n"
"}\n"
"QSlider::groove:horizontal {\n"
"    height: 5px; \n"
"    left:8px; right: 8px;\n"
"}")
        self.horizontalSlider_pulse_6.setMinimum(0)
        self.horizontalSlider_pulse_6.setMaximum(1000)
        self.horizontalSlider_pulse_6.setPageStep(1)
        self.horizontalSlider_pulse_6.setProperty("value", 500)
        self.horizontalSlider_pulse_6.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_pulse_6.setObjectName("horizontalSlider_pulse_6")
        self.lineEdit_6 = QtWidgets.QLineEdit(self.widget_id6)
        self.lineEdit_6.setGeometry(QtCore.QRect(44, 50, 41, 25))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        self.lineEdit_6.setFont(font)
        self.lineEdit_6.setAutoFillBackground(False)
        self.lineEdit_6.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-radius:0px;")
        self.lineEdit_6.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_6.setReadOnly(False)
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.label_left_2 = QtWidgets.QLabel(self.widget_id6)
        self.label_left_2.setGeometry(QtCore.QRect(85, 53, 36, 21))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(10)
        self.label_left_2.setFont(font)
        self.label_left_2.setStyleSheet("background-color: rgb(255, 255, 255， 0);")
        self.label_left_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_left_2.setObjectName("label_left_2")
        self.label_d6 = QtWidgets.QLabel(self.widget_id6)
        self.label_d6.setGeometry(QtCore.QRect(5, 87, 31, 16))
        font = QtGui.QFont()
        font.setFamily("DejaVu Sans")
        font.setPointSize(10)
        self.label_d6.setFont(font)
        self.label_d6.setStyleSheet("background-color: rgb(255, 255, 255， 0);")
        self.label_d6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_d6.setObjectName("label_d6")
        self.label_right_2 = QtWidgets.QLabel(self.widget_id6)
        self.label_right_2.setGeometry(QtCore.QRect(5, 53, 36, 21))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(10)
        self.label_right_2.setFont(font)
        self.label_right_2.setStyleSheet("background-color: rgb(255, 255, 255， 0);")
        self.label_right_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_right_2.setObjectName("label_right_2")
        self.horizontalSlider_dev_6 = QtWidgets.QSlider(self.widget_id6)
        self.horizontalSlider_dev_6.setGeometry(QtCore.QRect(35, 85, 50, 20))
        self.horizontalSlider_dev_6.setStyleSheet("background-color: rgb(255, 255, 255， 0);")
        self.horizontalSlider_dev_6.setMinimum(-125)
        self.horizontalSlider_dev_6.setMaximum(125)
        self.horizontalSlider_dev_6.setPageStep(1)
        self.horizontalSlider_dev_6.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_dev_6.setObjectName("horizontalSlider_dev_6")
        self.widget_5 = QtWidgets.QWidget(self.tab_1)
        self.widget_5.setGeometry(QtCore.QRect(910, 360, 281, 211))
        self.widget_5.setStyleSheet("#widget_5 {border:1px solid #242424;\n"
"border-color: rgb(200, 200, 200);}")
        self.widget_5.setObjectName("widget_5")
        self.label_action = QtWidgets.QLabel(self.widget_5)
        self.label_action.setGeometry(QtCore.QRect(5, 20, 111, 30))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(12)
        self.label_action.setFont(font)
        self.label_action.setObjectName("label_action")
        self.comboBox_action = QtWidgets.QComboBox(self.widget_5)
        self.comboBox_action.setGeometry(QtCore.QRect(120, 20, 71, 30))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.comboBox_action.setFont(font)
        self.comboBox_action.setStyleSheet("background-color: rgb(240, 240, 240);\n"
"color: rgb(0, 0, 0);")
        self.comboBox_action.setObjectName("comboBox_action")
        self.Button_RunAction = QtWidgets.QPushButton(self.widget_5)
        self.Button_RunAction.setGeometry(QtCore.QRect(10, 70, 140, 50))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(12)
        self.Button_RunAction.setFont(font)
        self.Button_RunAction.setStyleSheet("QPushButton{background-color: rgb(255, 165, 0);}\n"
"QPushButton:hover{background-color:  rgb(255, 210, 0);}\n"
"QPushButton{border-radius:5px;}")
        self.Button_RunAction.setObjectName("Button_RunAction")
        self.Button_StopAction = QtWidgets.QPushButton(self.widget_5)
        self.Button_StopAction.setGeometry(QtCore.QRect(160, 70, 110, 50))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(12)
        self.Button_StopAction.setFont(font)
        self.Button_StopAction.setStyleSheet("QPushButton{background-color: rgb(255, 165, 0);}\n"
"QPushButton:hover{background-color:  rgb(255, 210, 0);}\n"
"QPushButton{border-radius:5px;}")
        self.Button_StopAction.setObjectName("Button_StopAction")
        self.Button_Quit = QtWidgets.QPushButton(self.widget_5)
        self.Button_Quit.setGeometry(QtCore.QRect(100, 135, 100, 60))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(12)
        self.Button_Quit.setFont(font)
        self.Button_Quit.setStyleSheet("QPushButton{background-color: rgb(255, 165, 0);}\n"
"QPushButton:hover{background-color:  rgb(255, 210, 0);}\n"
"QPushButton{border-radius:5px;}")
        self.Button_Quit.setObjectName("Button_Quit")
        self.Button_Reflash = QtWidgets.QPushButton(self.widget_5)
        self.Button_Reflash.setGeometry(QtCore.QRect(200, 12, 71, 41))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(12)
        self.Button_Reflash.setFont(font)
        self.Button_Reflash.setStyleSheet("QPushButton{background-color: rgb(255, 165, 0);}\n"
"QPushButton:hover{background-color:  rgb(255, 210, 0);}\n"
"QPushButton{border-radius:5px;}")
        self.Button_Reflash.setObjectName("Button_Reflash")
        self.widget_3 = QtWidgets.QWidget(self.tab_1)
        self.widget_3.setGeometry(QtCore.QRect(670, 360, 90, 211))
        self.widget_3.setStyleSheet("#widget_3 {border:1px solid #242424;\n"
"border-color: rgb(200, 200, 200);}")
        self.widget_3.setObjectName("widget_3")
        self.checkBox = QtWidgets.QCheckBox(self.widget_3)
        self.checkBox.setGeometry(QtCore.QRect(20, 40, 61, 41))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(12)
        self.checkBox.setFont(font)
        self.checkBox.setObjectName("checkBox")
        self.Button_Run = QtWidgets.QPushButton(self.widget_3)
        self.Button_Run.setGeometry(QtCore.QRect(10, 100, 70, 81))
        font = QtGui.QFont()
        font.setFamily("SimHei")
        font.setPointSize(20)
        self.Button_Run.setFont(font)
        self.Button_Run.setStyleSheet("QPushButton{background-color: rgb(255, 165, 0);}\n"
"QPushButton:hover{background-color:  rgb(255, 210, 0);}\n"
"QPushButton{border-radius:5px;}")
        self.Button_Run.setIconSize(QtCore.QSize(14, 14))
        self.Button_Run.setObjectName("Button_Run")
        self.widget_2 = QtWidgets.QWidget(self.tab_1)
        self.widget_2.setGeometry(QtCore.QRect(485, 360, 181, 211))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        self.widget_2.setFont(font)
        self.widget_2.setStyleSheet("#widget_2 {border:1px solid #242424;\n"
"border-color: rgb(200, 200, 200);}")
        self.widget_2.setObjectName("widget_2")
        self.Button_ReadDeviation = QtWidgets.QPushButton(self.widget_2)
        self.Button_ReadDeviation.setGeometry(QtCore.QRect(10, 15, 160, 51))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(12)
        self.Button_ReadDeviation.setFont(font)
        self.Button_ReadDeviation.setStyleSheet("QPushButton{background-color: rgb(255, 165, 0);}\n"
"QPushButton:hover{background-color:  rgb(255, 210, 0);}\n"
"QPushButton{border-radius:5px;}")
        self.Button_ReadDeviation.setObjectName("Button_ReadDeviation")
        self.Button_DownloadDeviation = QtWidgets.QPushButton(self.widget_2)
        self.Button_DownloadDeviation.setGeometry(QtCore.QRect(10, 80, 160, 51))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(12)
        self.Button_DownloadDeviation.setFont(font)
        self.Button_DownloadDeviation.setStyleSheet("QPushButton{background-color: rgb(255, 165, 0);}\n"
"QPushButton:hover{background-color:  rgb(255, 210, 0);}\n"
"QPushButton{border-radius:5px;}")
        self.Button_DownloadDeviation.setObjectName("Button_DownloadDeviation")
        self.Button_ReSetServos = QtWidgets.QPushButton(self.widget_2)
        self.Button_ReSetServos.setGeometry(QtCore.QRect(10, 140, 160, 51))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(12)
        self.Button_ReSetServos.setFont(font)
        self.Button_ReSetServos.setStyleSheet("QPushButton{background-color: rgb(255, 165, 0);}\n"
"QPushButton:hover{background-color:  rgb(255, 210, 0);}\n"
"QPushButton{border-radius:5px;}")
        self.Button_ReSetServos.setObjectName("Button_ReSetServos")
        self.tableWidget = QtWidgets.QTableWidget(self.tab_1)
        self.tableWidget.setGeometry(QtCore.QRect(485, 0, 711, 210))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tableWidget.sizePolicy().hasHeightForWidth())
        self.tableWidget.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(11)
        self.tableWidget.setFont(font)
        self.tableWidget.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.tableWidget.setStyleSheet("border:1px solid #242424;\n"
"border-color: rgb(200, 200, 200);")
        self.tableWidget.setTextElideMode(QtCore.Qt.ElideMiddle)
        self.tableWidget.setRowCount(0)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(9)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignVCenter)
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(11)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignTop)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignTop)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignTop)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignTop)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignTop)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignTop)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignTop)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignTop)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(8, item)
        self.tableWidget.horizontalHeader().setDefaultSectionSize(79)
        self.tableWidget.horizontalHeader().setMinimumSectionSize(20)
        self.tableWidget.horizontalHeader().setSortIndicatorShown(True)
        self.tableWidget.verticalHeader().setVisible(False)
        self.tableWidget.verticalHeader().setDefaultSectionSize(22)
        self.tableWidget.verticalHeader().setMinimumSectionSize(22)
        self.widget_4 = QtWidgets.QWidget(self.tab_1)
        self.widget_4.setGeometry(QtCore.QRect(765, 360, 141, 211))
        self.widget_4.setStyleSheet("#widget_4 {border:1px solid #242424;\n"
"border-color: rgb(200, 200, 200);}")
        self.widget_4.setObjectName("widget_4")
        self.Button_OpenActionGroup = QtWidgets.QPushButton(self.widget_4)
        self.Button_OpenActionGroup.setGeometry(QtCore.QRect(5, 15, 130, 51))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(12)
        self.Button_OpenActionGroup.setFont(font)
        self.Button_OpenActionGroup.setStyleSheet("QPushButton{background-color: rgb(255, 165, 0);}\n"
"QPushButton:hover{background-color:  rgb(255, 210, 0);}\n"
"QPushButton{border-radius:5px;}")
        self.Button_OpenActionGroup.setObjectName("Button_OpenActionGroup")
        self.Button_SaveActionGroup = QtWidgets.QPushButton(self.widget_4)
        self.Button_SaveActionGroup.setGeometry(QtCore.QRect(5, 80, 130, 51))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(12)
        self.Button_SaveActionGroup.setFont(font)
        self.Button_SaveActionGroup.setStyleSheet("QPushButton{background-color: rgb(255, 165, 0);}\n"
"QPushButton:hover{background-color:  rgb(255, 210, 0);}\n"
"QPushButton{border-radius:5px;}")
        self.Button_SaveActionGroup.setObjectName("Button_SaveActionGroup")
        self.Button_TandemActionGroup = QtWidgets.QPushButton(self.widget_4)
        self.Button_TandemActionGroup.setGeometry(QtCore.QRect(5, 145, 130, 51))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(12)
        self.Button_TandemActionGroup.setFont(font)
        self.Button_TandemActionGroup.setStyleSheet("QPushButton{background-color: rgb(255, 165, 0);}\n"
"QPushButton:hover{background-color:  rgb(255, 210, 0);}\n"
"QPushButton{border-radius:5px;}")
        self.Button_TandemActionGroup.setObjectName("Button_TandemActionGroup")
        self.widget_1 = QtWidgets.QWidget(self.tab_1)
        self.widget_1.setGeometry(QtCore.QRect(485, 240, 711, 111))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.widget_1.setFont(font)
        self.widget_1.setStyleSheet("#widget_1 {border:1px solid #242424;\n"
"border-color: rgb(200, 200, 200);}")
        self.widget_1.setObjectName("widget_1")
        self.label_time = QtWidgets.QLabel(self.widget_1)
        self.label_time.setGeometry(QtCore.QRect(20, 20, 111, 31))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(11)
        self.label_time.setFont(font)
        self.label_time.setObjectName("label_time")
        self.lineEdit_time = QtWidgets.QLineEdit(self.widget_1)
        self.lineEdit_time.setGeometry(QtCore.QRect(140, 20, 41, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.lineEdit_time.setFont(font)
        self.lineEdit_time.setMaxLength(30000)
        self.lineEdit_time.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_time.setObjectName("lineEdit_time")
        self.Button_AddAction = QtWidgets.QPushButton(self.widget_1)
        self.Button_AddAction.setGeometry(QtCore.QRect(350, 10, 110, 41))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(11)
        self.Button_AddAction.setFont(font)
        self.Button_AddAction.setStyleSheet("QPushButton{background-color: rgb(255, 165, 0);}\n"
"QPushButton:hover{background-color:  rgb(255, 210, 0);}\n"
"QPushButton{border-radius:5px;}")
        self.Button_AddAction.setObjectName("Button_AddAction")
        self.Button_DelectAction = QtWidgets.QPushButton(self.widget_1)
        self.Button_DelectAction.setGeometry(QtCore.QRect(350, 60, 110, 17))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(11)
        self.Button_DelectAction.setFont(font)
        self.Button_DelectAction.setStyleSheet("QPushButton{background-color: rgb(255, 165, 0);}\n"
"QPushButton:hover{background-color:  rgb(255, 210, 0);}\n"
"QPushButton{border-radius:5px;}")
        self.Button_DelectAction.setObjectName("Button_DelectAction")
        self.Button_UpdateAction = QtWidgets.QPushButton(self.widget_1)
        self.Button_UpdateAction.setGeometry(QtCore.QRect(470, 10, 110, 41))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(11)
        self.Button_UpdateAction.setFont(font)
        self.Button_UpdateAction.setStyleSheet("QPushButton{background-color: rgb(255, 165, 0);}\n"
"QPushButton:hover{background-color:  rgb(255, 210, 0);}\n"
"QPushButton{border-radius:5px;}")
        self.Button_UpdateAction.setObjectName("Button_UpdateAction")
        self.Button_InsertAction = QtWidgets.QPushButton(self.widget_1)
        self.Button_InsertAction.setGeometry(QtCore.QRect(470, 60, 110, 41))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(11)
        self.Button_InsertAction.setFont(font)
        self.Button_InsertAction.setStyleSheet("QPushButton{background-color: rgb(255, 165, 0);}\n"
"QPushButton:hover{background-color:  rgb(255, 210, 0);}\n"
"QPushButton{border-radius:5px;}")
        self.Button_InsertAction.setObjectName("Button_InsertAction")
        self.Button_ServoPowerDown = QtWidgets.QPushButton(self.widget_1)
        self.Button_ServoPowerDown.setGeometry(QtCore.QRect(220, 10, 120, 41))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(11)
        self.Button_ServoPowerDown.setFont(font)
        self.Button_ServoPowerDown.setStyleSheet("QPushButton{background-color: rgb(255, 165, 0);}\n"
"QPushButton:hover{background-color:  rgb(255, 210, 0);}\n"
"QPushButton{border-radius:5px;}")
        self.Button_ServoPowerDown.setObjectName("Button_ServoPowerDown")
        self.Button_AngularReadback = QtWidgets.QPushButton(self.widget_1)
        self.Button_AngularReadback.setGeometry(QtCore.QRect(220, 60, 120, 41))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(11)
        self.Button_AngularReadback.setFont(font)
        self.Button_AngularReadback.setStyleSheet("QPushButton{background-color: rgb(255, 165, 0);}\n"
"QPushButton:hover{background-color:  rgb(255, 210, 0);}\n"
"QPushButton{border-radius:5px;}")
        self.Button_AngularReadback.setObjectName("Button_AngularReadback")
        self.Button_MoveUpAction = QtWidgets.QPushButton(self.widget_1)
        self.Button_MoveUpAction.setGeometry(QtCore.QRect(590, 10, 110, 41))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(11)
        self.Button_MoveUpAction.setFont(font)
        self.Button_MoveUpAction.setStyleSheet("QPushButton{background-color: rgb(255, 165, 0);}\n"
"QPushButton:hover{background-color:  rgb(255, 210, 0);}\n"
"QPushButton{border-radius:5px;}")
        self.Button_MoveUpAction.setObjectName("Button_MoveUpAction")
        self.Button_MoveDownAction = QtWidgets.QPushButton(self.widget_1)
        self.Button_MoveDownAction.setGeometry(QtCore.QRect(590, 60, 110, 41))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(11)
        self.Button_MoveDownAction.setFont(font)
        self.Button_MoveDownAction.setStyleSheet("QPushButton{background-color: rgb(255, 165, 0);}\n"
"QPushButton:hover{background-color:  rgb(255, 210, 0);}\n"
"QPushButton{border-radius:5px;}")
        self.Button_MoveDownAction.setObjectName("Button_MoveDownAction")
        self.label_time_2 = QtWidgets.QLabel(self.widget_1)
        self.label_time_2.setGeometry(QtCore.QRect(20, 60, 105, 31))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(11)
        self.label_time_2.setFont(font)
        self.label_time_2.setObjectName("label_time_2")
        self.label = QtWidgets.QLabel(self.widget_1)
        self.label.setGeometry(QtCore.QRect(190, 25, 16, 21))
        font = QtGui.QFont()
        font.setFamily("DejaVu Sans")
        font.setPointSize(8)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.label_5 = QtWidgets.QLabel(self.widget_1)
        self.label_5.setGeometry(QtCore.QRect(190, 65, 16, 21))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(12)
        self.label_5.setFont(font)
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.label_TotalTime = QtWidgets.QLabel(self.widget_1)
        self.label_TotalTime.setGeometry(QtCore.QRect(130, 65, 60, 20))
        self.label_TotalTime.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_TotalTime.setAlignment(QtCore.Qt.AlignCenter)
        self.label_TotalTime.setObjectName("label_TotalTime")
        self.Button_DelectAllAction = QtWidgets.QPushButton(self.widget_1)
        self.Button_DelectAllAction.setGeometry(QtCore.QRect(350, 83, 110, 17))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(11)
        self.Button_DelectAllAction.setFont(font)
        self.Button_DelectAllAction.setStyleSheet("QPushButton{background-color: rgb(255, 165, 0);}\n"
"QPushButton:hover{background-color:  rgb(255, 210, 0);}\n"
"QPushButton{border-radius:5px;}")
        self.Button_DelectAllAction.setObjectName("Button_DelectAllAction")
        self.widget_id5 = QtWidgets.QWidget(self.tab_1)
        self.widget_id5.setGeometry(QtCore.QRect(300, 330, 120, 110))
        self.widget_id5.setStyleSheet("background-color: rgb(255, 165, 0, 200);\n"
"border-radius:10px;")
        self.widget_id5.setObjectName("widget_id5")
        self.horizontalSlider_pulse_5 = QtWidgets.QSlider(self.widget_id5)
        self.horizontalSlider_pulse_5.setGeometry(QtCore.QRect(10, 20, 100, 22))
        self.horizontalSlider_pulse_5.setAutoFillBackground(False)
        self.horizontalSlider_pulse_5.setStyleSheet("QSlider{\n"
"    border-radius:0px;\n"
"     background-color: rgb(0, 0, 0);\n"
"}\n"
"\n"
"QSlider::handle {/*设置中间的那个滑动的键*/                           \n"
"    border: 10px solid rgb(255, 255, 255)\n"
"}\n"
"QSlider::handle:horizontal{\n"
"    width: -1px;\n"
"    margin: -4px; /* height */\n"
"}\n"
"QSlider::groove{\n"
"    background: rgb(10, 150, 200);\n"
"}\n"
"QSlider::groove:horizontal {\n"
"    height: 5px; \n"
"    left:8px; right: 8px;\n"
"}")
        self.horizontalSlider_pulse_5.setMinimum(100)
        self.horizontalSlider_pulse_5.setMaximum(900)
        self.horizontalSlider_pulse_5.setPageStep(1)
        self.horizontalSlider_pulse_5.setProperty("value", 500)
        self.horizontalSlider_pulse_5.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_pulse_5.setObjectName("horizontalSlider_pulse_5")
        self.label_ID5 = QtWidgets.QLabel(self.widget_id5)
        self.label_ID5.setGeometry(QtCore.QRect(50, 0, 32, 20))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        self.label_ID5.setFont(font)
        self.label_ID5.setStyleSheet("background-color: rgb(255, 255, 255， 0);\n"
"border-radius:0px;")
        self.label_ID5.setObjectName("label_ID5")
        self.lineEdit_5 = QtWidgets.QLineEdit(self.widget_id5)
        self.lineEdit_5.setGeometry(QtCore.QRect(40, 50, 41, 25))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        self.lineEdit_5.setFont(font)
        self.lineEdit_5.setAutoFillBackground(False)
        self.lineEdit_5.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-radius:0px;")
        self.lineEdit_5.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_5.setReadOnly(False)
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.label_up_3 = QtWidgets.QLabel(self.widget_id5)
        self.label_up_3.setGeometry(QtCore.QRect(85, 53, 31, 21))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(10)
        self.label_up_3.setFont(font)
        self.label_up_3.setStyleSheet("background-color: rgb(255, 255, 255， 0);")
        self.label_up_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_up_3.setObjectName("label_up_3")
        self.label_d5 = QtWidgets.QLabel(self.widget_id5)
        self.label_d5.setGeometry(QtCore.QRect(5, 87, 31, 16))
        font = QtGui.QFont()
        font.setFamily("DejaVu Sans")
        font.setPointSize(10)
        self.label_d5.setFont(font)
        self.label_d5.setStyleSheet("background-color: rgb(255, 255, 255， 0);")
        self.label_d5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_d5.setObjectName("label_d5")
        self.label_down_3 = QtWidgets.QLabel(self.widget_id5)
        self.label_down_3.setGeometry(QtCore.QRect(0, 53, 36, 21))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(10)
        self.label_down_3.setFont(font)
        self.label_down_3.setStyleSheet("background-color: rgb(255, 255, 255， 0);")
        self.label_down_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_down_3.setObjectName("label_down_3")
        self.horizontalSlider_dev_5 = QtWidgets.QSlider(self.widget_id5)
        self.horizontalSlider_dev_5.setGeometry(QtCore.QRect(35, 85, 50, 20))
        self.horizontalSlider_dev_5.setStyleSheet("background-color: rgb(255, 255, 255， 0);")
        self.horizontalSlider_dev_5.setMinimum(-125)
        self.horizontalSlider_dev_5.setMaximum(125)
        self.horizontalSlider_dev_5.setPageStep(1)
        self.horizontalSlider_dev_5.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_dev_5.setObjectName("horizontalSlider_dev_5")
        self.widget_id1 = QtWidgets.QWidget(self.tab_1)
        self.widget_id1.setGeometry(QtCore.QRect(20, 50, 120, 110))
        self.widget_id1.setStyleSheet("background-color: rgb(255, 165, 0, 200);\n"
"border-radius:10px;")
        self.widget_id1.setObjectName("widget_id1")
        self.label_ID1 = QtWidgets.QLabel(self.widget_id1)
        self.label_ID1.setGeometry(QtCore.QRect(45, 0, 41, 20))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        self.label_ID1.setFont(font)
        self.label_ID1.setStyleSheet("background-color: rgb(255, 255, 255， 0);\n"
"border-radius:0px;")
        self.label_ID1.setObjectName("label_ID1")
        self.horizontalSlider_pulse_1 = QtWidgets.QSlider(self.widget_id1)
        self.horizontalSlider_pulse_1.setGeometry(QtCore.QRect(10, 20, 100, 22))
        self.horizontalSlider_pulse_1.setAutoFillBackground(False)
        self.horizontalSlider_pulse_1.setStyleSheet("QSlider{\n"
"    border-radius:0px;\n"
"     background-color: rgb(0, 0, 0);\n"
"}\n"
"\n"
"QSlider::handle {/*设置中间的那个滑动的键*/                           \n"
"    border: 10px solid rgb(255, 255, 255)\n"
"}\n"
"QSlider::handle:horizontal{\n"
"    width: -1px;\n"
"    margin: -4px; /* height */\n"
"}\n"
"QSlider::groove{\n"
"    background: rgb(10, 150, 200);\n"
"}\n"
"QSlider::groove:horizontal {\n"
"    height: 5px; \n"
"    left:8px; right: 8px;\n"
"}")
        self.horizontalSlider_pulse_1.setMinimum(0)
        self.horizontalSlider_pulse_1.setMaximum(1000)
        self.horizontalSlider_pulse_1.setPageStep(1)
        self.horizontalSlider_pulse_1.setProperty("value", 500)
        self.horizontalSlider_pulse_1.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_pulse_1.setObjectName("horizontalSlider_pulse_1")
        self.lineEdit_1 = QtWidgets.QLineEdit(self.widget_id1)
        self.lineEdit_1.setGeometry(QtCore.QRect(47, 50, 38, 25))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_1.sizePolicy().hasHeightForWidth())
        self.lineEdit_1.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        self.lineEdit_1.setFont(font)
        self.lineEdit_1.setAutoFillBackground(False)
        self.lineEdit_1.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-radius:0px;")
        self.lineEdit_1.setMaxLength(1000)
        self.lineEdit_1.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_1.setDragEnabled(False)
        self.lineEdit_1.setReadOnly(False)
        self.lineEdit_1.setObjectName("lineEdit_1")
        self.horizontalSlider_dev_1 = QtWidgets.QSlider(self.widget_id1)
        self.horizontalSlider_dev_1.setGeometry(QtCore.QRect(35, 85, 50, 20))
        self.horizontalSlider_dev_1.setStyleSheet("background-color: rgb(255, 255, 255， 0);")
        self.horizontalSlider_dev_1.setMinimum(-125)
        self.horizontalSlider_dev_1.setMaximum(125)
        self.horizontalSlider_dev_1.setPageStep(1)
        self.horizontalSlider_dev_1.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_dev_1.setObjectName("horizontalSlider_dev_1")
        self.label_d1 = QtWidgets.QLabel(self.widget_id1)
        self.label_d1.setGeometry(QtCore.QRect(5, 87, 31, 16))
        font = QtGui.QFont()
        font.setFamily("DejaVu Sans")
        font.setPointSize(10)
        self.label_d1.setFont(font)
        self.label_d1.setStyleSheet("background-color: rgb(255, 255, 255， 0);")
        self.label_d1.setAlignment(QtCore.Qt.AlignCenter)
        self.label_d1.setObjectName("label_d1")
        self.label_open = QtWidgets.QLabel(self.widget_id1)
        self.label_open.setGeometry(QtCore.QRect(0, 55, 48, 21))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(10)
        self.label_open.setFont(font)
        self.label_open.setStyleSheet("background-color: rgb(255, 255, 255， 0);")
        self.label_open.setAlignment(QtCore.Qt.AlignCenter)
        self.label_open.setObjectName("label_open")
        self.label_close = QtWidgets.QLabel(self.widget_id1)
        self.label_close.setGeometry(QtCore.QRect(85, 55, 36, 21))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(10)
        self.label_close.setFont(font)
        self.label_close.setStyleSheet("background-color: rgb(255, 255, 255， 0);")
        self.label_close.setAlignment(QtCore.Qt.AlignCenter)
        self.label_close.setObjectName("label_close")
        self.widget_id4 = QtWidgets.QWidget(self.tab_1)
        self.widget_id4.setGeometry(QtCore.QRect(350, 210, 120, 110))
        self.widget_id4.setStyleSheet("background-color: rgb(255, 165, 0, 200);\n"
"border-radius:10px;")
        self.widget_id4.setObjectName("widget_id4")
        self.horizontalSlider_pulse_4 = QtWidgets.QSlider(self.widget_id4)
        self.horizontalSlider_pulse_4.setGeometry(QtCore.QRect(10, 20, 100, 22))
        self.horizontalSlider_pulse_4.setAutoFillBackground(False)
        self.horizontalSlider_pulse_4.setStyleSheet("QSlider{\n"
"    border-radius:0px;\n"
"     background-color: rgb(0, 0, 0);\n"
"}\n"
"\n"
"QSlider::handle {/*设置中间的那个滑动的键*/                           \n"
"    border: 10px solid rgb(255, 255, 255)\n"
"}\n"
"QSlider::handle:horizontal{\n"
"    width: -1px;\n"
"    margin: -4px; /* height */\n"
"}\n"
"QSlider::groove{\n"
"    background: rgb(10, 150, 200);\n"
"}\n"
"QSlider::groove:horizontal {\n"
"    height: 5px; \n"
"    left:8px; right: 8px;\n"
"}")
        self.horizontalSlider_pulse_4.setMinimum(0)
        self.horizontalSlider_pulse_4.setMaximum(1000)
        self.horizontalSlider_pulse_4.setPageStep(1)
        self.horizontalSlider_pulse_4.setProperty("value", 500)
        self.horizontalSlider_pulse_4.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_pulse_4.setObjectName("horizontalSlider_pulse_4")
        self.label_ID4 = QtWidgets.QLabel(self.widget_id4)
        self.label_ID4.setGeometry(QtCore.QRect(50, 0, 32, 20))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        self.label_ID4.setFont(font)
        self.label_ID4.setStyleSheet("background-color: rgb(255, 255, 255， 0);\n"
"border-radius:0px;")
        self.label_ID4.setObjectName("label_ID4")
        self.lineEdit_4 = QtWidgets.QLineEdit(self.widget_id4)
        self.lineEdit_4.setGeometry(QtCore.QRect(40, 50, 41, 25))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        self.lineEdit_4.setFont(font)
        self.lineEdit_4.setAutoFillBackground(False)
        self.lineEdit_4.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-radius:0px;")
        self.lineEdit_4.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_4.setReadOnly(False)
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.label_up_2 = QtWidgets.QLabel(self.widget_id4)
        self.label_up_2.setGeometry(QtCore.QRect(85, 53, 36, 21))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(10)
        self.label_up_2.setFont(font)
        self.label_up_2.setStyleSheet("background-color: rgb(255, 255, 255， 0);")
        self.label_up_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_up_2.setObjectName("label_up_2")
        self.label_d4 = QtWidgets.QLabel(self.widget_id4)
        self.label_d4.setGeometry(QtCore.QRect(5, 87, 31, 16))
        font = QtGui.QFont()
        font.setFamily("DejaVu Sans")
        font.setPointSize(10)
        self.label_d4.setFont(font)
        self.label_d4.setStyleSheet("background-color: rgb(255, 255, 255， 0);")
        self.label_d4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_d4.setObjectName("label_d4")
        self.label_down_2 = QtWidgets.QLabel(self.widget_id4)
        self.label_down_2.setGeometry(QtCore.QRect(5, 53, 31, 21))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(10)
        self.label_down_2.setFont(font)
        self.label_down_2.setStyleSheet("background-color: rgb(255, 255, 255， 0);")
        self.label_down_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_down_2.setObjectName("label_down_2")
        self.horizontalSlider_dev_4 = QtWidgets.QSlider(self.widget_id4)
        self.horizontalSlider_dev_4.setGeometry(QtCore.QRect(35, 85, 50, 20))
        self.horizontalSlider_dev_4.setStyleSheet("background-color: rgb(255, 255, 255， 0);")
        self.horizontalSlider_dev_4.setMinimum(-125)
        self.horizontalSlider_dev_4.setMaximum(125)
        self.horizontalSlider_dev_4.setPageStep(1)
        self.horizontalSlider_dev_4.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_dev_4.setObjectName("horizontalSlider_dev_4")
        self.widget_id2 = QtWidgets.QWidget(self.tab_1)
        self.widget_id2.setGeometry(QtCore.QRect(160, 50, 120, 110))
        self.widget_id2.setStyleSheet("background-color: rgb(255, 165, 0, 200);\n"
"border-radius:10px;")
        self.widget_id2.setObjectName("widget_id2")
        self.label_ID2 = QtWidgets.QLabel(self.widget_id2)
        self.label_ID2.setGeometry(QtCore.QRect(50, 0, 32, 20))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        self.label_ID2.setFont(font)
        self.label_ID2.setStyleSheet("background-color: rgb(255, 255, 255， 0);\n"
"border-radius:0px;")
        self.label_ID2.setObjectName("label_ID2")
        self.horizontalSlider_pulse_2 = QtWidgets.QSlider(self.widget_id2)
        self.horizontalSlider_pulse_2.setGeometry(QtCore.QRect(10, 20, 100, 22))
        self.horizontalSlider_pulse_2.setAutoFillBackground(False)
        self.horizontalSlider_pulse_2.setStyleSheet("QSlider{\n"
"    border-radius:0px;\n"
"     background-color: rgb(0, 0, 0);\n"
"}\n"
"\n"
"QSlider::handle {/*设置中间的那个滑动的键*/                           \n"
"    border: 10px solid rgb(255, 255, 255)\n"
"}\n"
"QSlider::handle:horizontal{\n"
"    width: -1px;\n"
"    margin: -4px; /* height */\n"
"}\n"
"QSlider::groove{\n"
"    background: rgb(10, 150, 200);\n"
"}\n"
"QSlider::groove:horizontal {\n"
"    height: 5px; \n"
"    left:8px; right: 8px;\n"
"}")
        self.horizontalSlider_pulse_2.setMinimum(50)
        self.horizontalSlider_pulse_2.setMaximum(950)
        self.horizontalSlider_pulse_2.setPageStep(1)
        self.horizontalSlider_pulse_2.setProperty("value", 500)
        self.horizontalSlider_pulse_2.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_pulse_2.setObjectName("horizontalSlider_pulse_2")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.widget_id2)
        self.lineEdit_2.setGeometry(QtCore.QRect(40, 50, 41, 25))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        self.lineEdit_2.setFont(font)
        self.lineEdit_2.setAutoFillBackground(False)
        self.lineEdit_2.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-radius:0px;")
        self.lineEdit_2.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_2.setReadOnly(False)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.label_right_1 = QtWidgets.QLabel(self.widget_id2)
        self.label_right_1.setGeometry(QtCore.QRect(0, 53, 36, 21))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(10)
        self.label_right_1.setFont(font)
        self.label_right_1.setStyleSheet("background-color: rgb(255, 255, 255， 0);")
        self.label_right_1.setAlignment(QtCore.Qt.AlignCenter)
        self.label_right_1.setObjectName("label_right_1")
        self.label_d2 = QtWidgets.QLabel(self.widget_id2)
        self.label_d2.setGeometry(QtCore.QRect(5, 87, 31, 16))
        font = QtGui.QFont()
        font.setFamily("DejaVu Sans")
        font.setPointSize(10)
        self.label_d2.setFont(font)
        self.label_d2.setStyleSheet("background-color: rgb(255, 255, 255， 0);")
        self.label_d2.setTextFormat(QtCore.Qt.AutoText)
        self.label_d2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_d2.setObjectName("label_d2")
        self.label_left_1 = QtWidgets.QLabel(self.widget_id2)
        self.label_left_1.setGeometry(QtCore.QRect(85, 53, 36, 21))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(10)
        self.label_left_1.setFont(font)
        self.label_left_1.setStyleSheet("background-color: rgb(255, 255, 255， 0);")
        self.label_left_1.setAlignment(QtCore.Qt.AlignCenter)
        self.label_left_1.setObjectName("label_left_1")
        self.horizontalSlider_dev_2 = QtWidgets.QSlider(self.widget_id2)
        self.horizontalSlider_dev_2.setGeometry(QtCore.QRect(35, 85, 50, 20))
        self.horizontalSlider_dev_2.setStyleSheet("background-color: rgb(255, 255, 255， 0);")
        self.horizontalSlider_dev_2.setMinimum(-125)
        self.horizontalSlider_dev_2.setMaximum(125)
        self.horizontalSlider_dev_2.setPageStep(1)
        self.horizontalSlider_dev_2.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_dev_2.setObjectName("horizontalSlider_dev_2")
        self.widget_id3 = QtWidgets.QWidget(self.tab_1)
        self.widget_id3.setGeometry(QtCore.QRect(290, 90, 120, 110))
        self.widget_id3.setStyleSheet("background-color: rgb(255, 165, 0, 200);\n"
"border-radius:10px;")
        self.widget_id3.setObjectName("widget_id3")
        self.label_ID3 = QtWidgets.QLabel(self.widget_id3)
        self.label_ID3.setGeometry(QtCore.QRect(50, 0, 32, 20))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        self.label_ID3.setFont(font)
        self.label_ID3.setStyleSheet("background-color: rgb(255, 255, 255， 0);\n"
"border-radius:0px;")
        self.label_ID3.setObjectName("label_ID3")
        self.horizontalSlider_pulse_3 = QtWidgets.QSlider(self.widget_id3)
        self.horizontalSlider_pulse_3.setGeometry(QtCore.QRect(10, 20, 100, 22))
        self.horizontalSlider_pulse_3.setAutoFillBackground(False)
        self.horizontalSlider_pulse_3.setStyleSheet("QSlider{\n"
"    border-radius:0px;\n"
"     background-color: rgb(0, 0, 0);\n"
"}\n"
"\n"
"QSlider::handle {/*设置中间的那个滑动的键*/                           \n"
"    border: 10px solid rgb(255, 255, 255)\n"
"}\n"
"QSlider::handle:horizontal{\n"
"    width: -1px;\n"
"    margin: -4px; /* height */\n"
"}\n"
"QSlider::groove{\n"
"    background: rgb(10, 150, 200);\n"
"}\n"
"QSlider::groove:horizontal {\n"
"    height: 5px; \n"
"    left:8px; right: 8px;\n"
"}")
        self.horizontalSlider_pulse_3.setMinimum(50)
        self.horizontalSlider_pulse_3.setMaximum(950)
        self.horizontalSlider_pulse_3.setPageStep(1)
        self.horizontalSlider_pulse_3.setProperty("value", 500)
        self.horizontalSlider_pulse_3.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_pulse_3.setObjectName("horizontalSlider_pulse_3")
        self.lineEdit_3 = QtWidgets.QLineEdit(self.widget_id3)
        self.lineEdit_3.setGeometry(QtCore.QRect(40, 50, 41, 25))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        self.lineEdit_3.setFont(font)
        self.lineEdit_3.setAutoFillBackground(False)
        self.lineEdit_3.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-radius:0px;")
        self.lineEdit_3.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_3.setReadOnly(False)
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.label_up_1 = QtWidgets.QLabel(self.widget_id3)
        self.label_up_1.setGeometry(QtCore.QRect(85, 53, 31, 21))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(10)
        self.label_up_1.setFont(font)
        self.label_up_1.setStyleSheet("background-color: rgb(255, 255, 255， 0);")
        self.label_up_1.setAlignment(QtCore.Qt.AlignCenter)
        self.label_up_1.setObjectName("label_up_1")
        self.label_d3 = QtWidgets.QLabel(self.widget_id3)
        self.label_d3.setGeometry(QtCore.QRect(5, 87, 31, 16))
        font = QtGui.QFont()
        font.setFamily("DejaVu Sans")
        font.setPointSize(10)
        self.label_d3.setFont(font)
        self.label_d3.setStyleSheet("background-color: rgb(255, 255, 255， 0);")
        self.label_d3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_d3.setObjectName("label_d3")
        self.label_down_1 = QtWidgets.QLabel(self.widget_id3)
        self.label_down_1.setGeometry(QtCore.QRect(5, 53, 36, 21))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(10)
        self.label_down_1.setFont(font)
        self.label_down_1.setStyleSheet("background-color: rgb(255, 255, 255， 0);")
        self.label_down_1.setAlignment(QtCore.Qt.AlignCenter)
        self.label_down_1.setObjectName("label_down_1")
        self.horizontalSlider_dev_3 = QtWidgets.QSlider(self.widget_id3)
        self.horizontalSlider_dev_3.setGeometry(QtCore.QRect(35, 85, 50, 20))
        self.horizontalSlider_dev_3.setStyleSheet("background-color: rgb(255, 255, 255， 0);")
        self.horizontalSlider_dev_3.setMinimum(-125)
        self.horizontalSlider_dev_3.setMaximum(125)
        self.horizontalSlider_dev_3.setPageStep(1)
        self.horizontalSlider_dev_3.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_dev_3.setObjectName("horizontalSlider_dev_3")
        self.frame = QtWidgets.QFrame(self.tab_1)
        self.frame.setGeometry(QtCore.QRect(-15, 5, 498, 561))
        self.frame.setStyleSheet("background-image: url(:/resources/arm.png);")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.radioButton_zn = QtWidgets.QRadioButton(self.frame)
        self.radioButton_zn.setGeometry(QtCore.QRect(20, 10, 61, 27))
        self.radioButton_zn.setObjectName("radioButton_zn")
        self.radioButton_en = QtWidgets.QRadioButton(self.frame)
        self.radioButton_en.setGeometry(QtCore.QRect(100, 10, 81, 27))
        self.radioButton_en.setObjectName("radioButton_en")
        self.action_group_name = QtWidgets.QLabel(self.tab_1)
        self.action_group_name.setGeometry(QtCore.QRect(485, 215, 711, 20))
        self.action_group_name.setText("")
        self.action_group_name.setAlignment(QtCore.Qt.AlignCenter)
        self.action_group_name.setObjectName("action_group_name")
        self.frame.raise_()
        self.widget_id6.raise_()
        self.widget_5.raise_()
        self.widget_3.raise_()
        self.widget_2.raise_()
        self.tableWidget.raise_()
        self.widget_4.raise_()
        self.widget_1.raise_()
        self.widget_id5.raise_()
        self.widget_id1.raise_()
        self.widget_id4.raise_()
        self.widget_id2.raise_()
        self.widget_id3.raise_()
        self.action_group_name.raise_()
        self.tabWidget.addTab(self.tab_1, "")

        self.retranslateUi(Form)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "arm"))
        self.label_ID6.setText(_translate("Form", "ID:6"))
        self.lineEdit_6.setText(_translate("Form", "500"))
        self.label_left_2.setText(_translate("Form", "<html><head/><body><p align=\"center\">左</p></body></html>"))
        self.label_d6.setText(_translate("Form", "0"))
        self.label_right_2.setText(_translate("Form", "<html><head/><body><p align=\"center\">右</p></body></html>"))
        self.label_action.setText(_translate("Form", "动作组："))
        self.Button_RunAction.setText(_translate("Form", "动作组运行"))
        self.Button_StopAction.setText(_translate("Form", "停止"))
        self.Button_Quit.setText(_translate("Form", "退出"))
        self.Button_Reflash.setText(_translate("Form", "刷新"))
        self.checkBox.setText(_translate("Form", "循环"))
        self.Button_Run.setText(_translate("Form", "运行"))
        self.Button_ReadDeviation.setText(_translate("Form", "读取偏差"))
        self.Button_DownloadDeviation.setText(_translate("Form", "下载偏差"))
        self.Button_ReSetServos.setText(_translate("Form", "复位舵机"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("Form", "编号"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("Form", "时间"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("Form", "ID:1"))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("Form", "ID:2"))
        item = self.tableWidget.horizontalHeaderItem(5)
        item.setText(_translate("Form", "ID:3"))
        item = self.tableWidget.horizontalHeaderItem(6)
        item.setText(_translate("Form", "ID:4"))
        item = self.tableWidget.horizontalHeaderItem(7)
        item.setText(_translate("Form", "ID:5"))
        item = self.tableWidget.horizontalHeaderItem(8)
        item.setText(_translate("Form", "ID:6"))
        self.Button_OpenActionGroup.setText(_translate("Form", "打开动作文件"))
        self.Button_SaveActionGroup.setText(_translate("Form", "保存动作文件"))
        self.Button_TandemActionGroup.setText(_translate("Form", "串联动作文件"))
        self.label_time.setText(_translate("Form", "动作时间"))
        self.lineEdit_time.setText(_translate("Form", "1000"))
        self.Button_AddAction.setText(_translate("Form", "添加动作"))
        self.Button_DelectAction.setText(_translate("Form", "删除动作"))
        self.Button_UpdateAction.setText(_translate("Form", "更新动作"))
        self.Button_InsertAction.setText(_translate("Form", "插入动作"))
        self.Button_ServoPowerDown.setText(_translate("Form", "马达掉电"))
        self.Button_AngularReadback.setText(_translate("Form", "角度回读"))
        self.Button_MoveUpAction.setText(_translate("Form", "上移动作"))
        self.Button_MoveDownAction.setText(_translate("Form", "下移动作"))
        self.label_time_2.setText(_translate("Form", "总时长"))
        self.label.setText(_translate("Form", "ms"))
        self.label_5.setText(_translate("Form", "s"))
        self.label_TotalTime.setText(_translate("Form", "0"))
        self.Button_DelectAllAction.setText(_translate("Form", "删除全部"))
        self.label_ID5.setText(_translate("Form", "ID:5"))
        self.lineEdit_5.setText(_translate("Form", "500"))
        self.label_up_3.setText(_translate("Form", "<html><head/><body><p align=\"center\">上</p></body></html>"))
        self.label_d5.setText(_translate("Form", "0"))
        self.label_down_3.setText(_translate("Form", "<html><head/><body><p align=\"center\">下</p></body></html>"))
        self.label_ID1.setText(_translate("Form", "ID:1"))
        self.lineEdit_1.setText(_translate("Form", "500"))
        self.label_d1.setText(_translate("Form", "0"))
        self.label_open.setText(_translate("Form", "<html><head/><body><p align=\"center\">开</p><p align=\"justify\"><br/></p></body></html>"))
        self.label_close.setText(_translate("Form", "<html><head/><body><p align=\"center\">合</p></body></html>"))
        self.label_ID4.setText(_translate("Form", "ID:4"))
        self.lineEdit_4.setText(_translate("Form", "500"))
        self.label_up_2.setText(_translate("Form", "<html><head/><body><p align=\"center\">上</p></body></html>"))
        self.label_d4.setText(_translate("Form", "0"))
        self.label_down_2.setText(_translate("Form", "<html><head/><body><p align=\"center\">下</p></body></html>"))
        self.label_ID2.setText(_translate("Form", "ID:2"))
        self.lineEdit_2.setText(_translate("Form", "500"))
        self.label_right_1.setText(_translate("Form", "<html><head/><body><p align=\"center\">右</p></body></html>"))
        self.label_d2.setText(_translate("Form", "0"))
        self.label_left_1.setText(_translate("Form", "<html><head/><body><p align=\"center\">左</p></body></html>"))
        self.label_ID3.setText(_translate("Form", "ID:3"))
        self.lineEdit_3.setText(_translate("Form", "500"))
        self.label_up_1.setText(_translate("Form", "<html><head/><body><p align=\"center\">上</p></body></html>"))
        self.label_d3.setText(_translate("Form", "0"))
        self.label_down_1.setText(_translate("Form", "<html><head/><body><p align=\"center\">下</p></body></html>"))
        self.radioButton_zn.setText(_translate("Form", "中文"))
        self.radioButton_en.setText(_translate("Form", "English"))
